### ISSUE TITLE
ValueError: could not broadcast input array from shape (268,268,3) into shape (268,266,3)

### ISSUE THREAD

**Issue by anubratabhowmick** [Neural-Dynamics-of-Visual-Cognition-FUB/Algonauts2021_devkit#2]
While running python feature_extraction/generate_features_alexnet.py, I receive the error 
Traceback (most recent call last):
  File "feature_extraction/generate_features_alexnet.py", line 224, in <module>
    main()
  File "feature_extraction/generate_features_alexnet.py", line 215, in main
    get_activations_and_save(model, video_list, activations_dir)
  File "feature_extraction/generate_features_alexnet.py", line 124, in get_activations_and_save
    vid,num_frames = get_video_from_mp4(video_file, sampling_rate)
  File "feature_extraction/generate_features_alexnet.py", line 63, in get_video_from_mp4
    (ret, buf[int((fc - 1) / sampling_rate)]) = cap.read()
ValueError: could not broadcast input array from shape (268,268,3) into shape (268,266,3)

Nothing in the code has been changed, as I am trying to extract the alexnet features.

**Comment by kshitijd20** [comment]
Are you trying to extract features of videos from the dataset or some other videos? It should not happen for the dataset videos. Can you try printing the name of videofile before line 124 `print(video_file)`  to find out which video is problematic.

**Comment by anubratabhowmick** [comment]
Hi, It's the first video only

video_file::  ./AlgonautsVideos268_All_30fpsmax/0001_0-0-1-6-7-2-8-0-17500167280.mp4

I am not using any other videos. Just the ones from the dataset.

**Comment by kshitijd20** [comment]
First, I would like to request you to download the latest code where we fixed 2 key frame reading bugs by using `git pull` .

Then replace the while loop in line 60 by following code and please tell me what is the print output that you get for first video


```
    while fc < frameCount and ret:
        fc += 1
        (ret, frame) = cap.read()
        print(frameCount,frameWidth,frameHeight)
        print(frame.shape)
        break
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        if fc % sampling_rate == 0:
            buf[int((fc - 1) / sampling_rate)] = frame
```

**Comment by anubratabhowmick** [comment]
After downloading the latest changes and updating the while loop with this one, it works.

**Comment by kshitijd20** [comment]
Can you please try again without replacing the while loop in latest code and see if it still works? In the above replacement I added a break in while loop so it will only read first frame. Let me know if it worked

**Comment by anubratabhowmick** [comment]
<img width="1219" alt="Screenshot 2021-06-05 at 11 57 48 PM" src="https://user-images.githubusercontent.com/7466987/120906466-d7cf2d00-c659-11eb-9a72-b5c78c14fee9.png">

See this, please!

**Comment by anubratabhowmick** [comment]
These are the printout from your added while loop. I noticed the break later as in one case, I encountered a NoneType

**Comment by anubratabhowmick** [comment]
<img width="1439" alt="Screenshot 2021-06-06 at 12 02 42 AM" src="https://user-images.githubusercontent.com/7466987/120906538-86736d80-c65a-11eb-92eb-e436307dce3e.png">


Same error if I use the original while loop!
All the video dimensions are not same

**Comment by kshitijd20** [comment]
I am not sure why openCV is reading incorrect framewidth in multiple videos. Since I cannot reproduce same error it is difficult to debug. For now replace the function with this and check if it works. Here instead of initializing a numpy array with fixed framewidth and frameheight I append all the frames to a list and convert to numpy array later. Please let me know if it fixed your issue

```
def get_video_from_mp4(file, sampling_rate):
    """This function takes a mp4 video file as input and returns
    an array of frames in numpy format.

    Parameters
    ----------
    file : str
        path to mp4 video file
    sampling_rate : int
        how many frames to skip when doing frame sampling.

    Returns
    -------
    video: np.array

    num_frames: int
        number of frames extracted

    """
    cap = cv2.VideoCapture(file)
    fc = 0
    frameCount = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    ret = True
    buf = []
    while fc < frameCount and ret:
        fc += 1
        (ret, frame) = cap.read()
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        if fc % sampling_rate == 0:
            buf.append(frame)
    
    buf = np.array(buf)

    cap.release()
    return np.expand_dims(buf, axis=0),int(frameCount / sampling_rate)
```

**Comment by anubratabhowmick** [comment]
It works for now. 
1. I also encountered NoneType in frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
2. I encountered frame 22 out of bounds error in mg =  vid[0,frame,:,:,:] (159 line) 

I bypassed them for now and it's working currently. I'll let you know if I come across any major developments.

**Comment by kshitijd20** [comment]
Hi can you please try downloading the latest code and use it to extract features? I have updated the code to use decord to read videos instead of opencv. This should hopefully fix the issue.

**Comment by anubratabhowmick** [comment]
Yes, it worked like a charm now!
Thanks for this. Maybe it's just a mac issue, but that was really something.
