### ISSUE TITLE
Bugs in get_video_from_mp4(file, sampling_rate)

### ISSUE THREAD

**Issue by rmldj** [Neural-Dynamics-of-Visual-Cognition-FUB/Algonauts2021_devkit#3]
There are two rather serious bugs in the function `get_video_from_mp4(file, sampling_rate)`.

1. The first comes from a peculiarity of opencv which by default uses the BGR ordering instead of RGB. Therefore the extracted frames have BGR ordering (you can check it by displaying them using `matplotlib.pyplot.imshow`. You will see that the colors are completely off.). This is a serious problem since later the frames are fed to neural networks which were pretrained on standard images with RGB ordering - this may adversely impact the extracted features.
2. The second bug comes from the code dealing with subsampling:
```
    ret = True
    while fc < frameCount and ret:
        fc += 1
        if fc % sampling_rate == 0:
            (ret, buf[int((fc - 1) / sampling_rate)]) = cap.read()
``` 
Here `cap.read()` is called every `sampling_rate` iterations, but what this does is that the output comprises **all** frames from the **first 1/4 of the clip** (if `sampling_rate=4` as in the script). Consequently the Alexnet features are constructed only from the beginning 1/4 of all video clips. In order to do what was intended, `cap.read()` should be called at every iteration, while the saving to `buf` should be done only every `sampling_rate` frames.

Both of these problems can be corrected by the following modifications:
```
    while fc < frameCount and ret:
        fc += 1
        (ret, frame) = cap.read()
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        if fc % sampling_rate == 0:
            buf[int((fc - 1) / sampling_rate)] = frame
```

I guess it would be good to inform all participants of the challenge about these problems as I think everyone would be using the provided code for extracting frames from mp4.

**Comment by kshitijd20** [comment]
Thanks so much for reporting the bugs and providing the suggested change. I have updated the code and we will send a message to all the participants on next week about these issues after updating the scores from our baseline. 

I am sorry for missing the bug and the incovenience thus caused.

**Comment by kshitijd20** [comment]
We have fixed the issue, updated the baseline score and notified the participants via codalab. Thank you again for reporting. I am closing this issue.
